services:
  - type: web
    name: productos-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn mi_proyecto.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_proyecto.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: api-django-uwx1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: productos-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://api-django-uwx1.onrender.com,https://api-django-chi.vercel.app,http://localhost:3000

databases:
  - name: productos-db
    plan: free
    databaseName: productos_0maa
    user: productos_0maa_user
