# Generated by Django 5.2.5 on 2025-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero_ot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número OT'),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_trabajo_pdf',
            field=models.BinaryField(blank=True, null=True, verbose_name='PDF OT'),
        ),
    ]
