# Generated by Django 5.2.5 on 2025-09-20 23:27

import django.core.validators
import django.utils.timezone
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_numero_ot_producto_orden_trabajo_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_ot',
            field=models.IntegerField(blank=True, help_text='Número de Orden de Trabajo', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número OT'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='orden_trabajo_pdf',
            field=models.BinaryField(blank=True, help_text='Archivo PDF de la Orden de Trabajo', null=True, validators=[productos.models.validate_pdf_file], verbose_name='PDF OT'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto (mínimo $0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Cantidad disponible en stock', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='productos_p_precio_d043df_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='productos_p_activo_31f808_idx'),
        ),
    ]
